name = "SymQM"
uuid = "a7deda02-319b-49aa-bebb-11fe90385be0"
version = "1.0.0-DEV"
authors = ["Gavin <gavin.rockwood@gmail.com> and contributors"]

[deps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
TermInterface = "8ea1fca8-c5ef-4a55-8b96-4e9afe9c9a3c"

[compat]
LaTeXStrings = "1.4.0"
Latexify = "0.16.10"
Reexport = "1.2.2"
Revise = "3.10.0"
SymbolicUtils = "3.32.0"
Symbolics = "6.55.0"
TermInterface = "2.0.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
